# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_username', models.CharField(max_length=50)),
                ('user_comment', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('biography', models.CharField(max_length=1000)),
                ('profile_picture', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=5000)),
                ('date', models.IntegerField(max_length=100)),
                ('likes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='commments',
            name='userPosts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.UserPosts'),
        ),
    ]
