# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='date',
            field=models.IntegerField(verbose_name=100),
        ),
    ]
